export const AJAX_CALL_START = 'AJAX_CALL_START';
export const AJAX_CALL_END = 'AJAX_CALL_END';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

/* LOADER START */
// export const LOADER_ERROR = 'LOADER_ERROR';
// //Loading
// export const LOADER_IS_LOADING = 'LOADER_IS_LOADING';
// export const LOADER_IS_PENDING = 'LOADER_IS_PENDING';
// export const LOADER_IS_COMPLETE = 'LOADER_IS_COMPLETE';
// /* LOADER END */

/*COURSES START */
export const LOAD_AUTHORS_SUCCESS= 'LOAD_AUTHORS_SUCCESS';
export const LOAD_COURSES_SUCCESS= 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS= 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS= 'UPDATE_COURSE_SUCCESS';

export const CREATE_COURSE= 'CREATE_COURSE';
export const UPDATE_COURSE= 'UPDATE_COURSE';
export const DELETE_COURSE= 'DELETE_COURSE';
/*COURSES END */

